### ISSUE TITLE
How to "install" the package

### ISSUE THREAD

**Issue by buhtz** [breezy-team/setuptools-gettext#22]
I never used a plugin for setuptools.

Your readme says that there are default options then can be overwritten by settings in the pyproject.toml.
What if I want to use the default options and don't write anything "setuptools-gettext" specific in the pyproject.toml?
How do I "run" your package?

Currently I do prepare some sample projects to illustrate several use cases for Python Packaging. Using GNU gettext po/mo-files is one of them. But I am not sure how to deal with it:

https://codeberg.org/buhtz/tech-demo-python-packaging/src/branch/main/03_i18n_helloworld

Maybe you can have a look at my pyproject.toml there.

**Comment by jelmer** [comment]
Just add it as a build dependency in whatever your Python build backend is - how that works depends on the build backend you're using. I've added an example for setuptools using pyproject.toml in README.md.
