### ISSUE TITLE
"tomli" package not found

### ISSUE THREAD

**Issue by buhtz** [breezy-team/setuptools-gettext#24]
I installed my own project (using setuptools-gettext in the pyproject.toml as an requirement) with `python3 -m pip install -e .`.

```
        File "/tmp/pip-build-env-go__a_yf/overlay/lib/python3.9/site-packages/setuptools_gettext/__init__.py", line 247, in pyprojecttoml_config
          from tomli import load as toml_load
      ModuleNotFoundError: No module named 'tomli'
```

But I installed "tomli". I can run `python3 -c "import tomli"` without errors or exceptions.

I do use Debian 11 with Python 3.9.2.

**Comment by jelmer** [comment]
File "/tmp/pip-build-env-go__a_yf/overlay/lib/python3.9/site-packages/setuptools_gettext/__init__.py", line 247, in pyprojecttoml_config

How are you running the project that's using setuptools-gettext? This is not a path that's included in PYTHONPATH on Debian by default.

**Comment by buhtz** [comment]
It is my [`tech-demo-python-packaging`](https://codeberg.org/buhtz/tech-demo-python-packaging) repo.

    $ git clone https://codeberg.org/buhtz/tech-demo-python-packaging.git
    $ cd tech*
    $ cd 03*
    $ python3 -m pip install --editable .
    $ helloworldint
