### ISSUE TITLE
Python 3.12 distutils removal

### ISSUE THREAD

**Issue by TomaSajt** [breezy-team/setuptools-gettext#51]
According to [PEP632](https://peps.python.org/pep-0632/), the `distutils` package was removed in Python 3.12

Is it possible to replace the dependency somehow?

**Comment by jelmer** [comment]
Is there a dependency left? I thought I'd replaced all of them.

**Comment by mweinelt** [comment]
https://github.com/breezy-team/setuptools-gettext/blob/master/setuptools_gettext/__init__.py#L27

**Comment by TomaSajt** [comment]
Thank you for the fix :)
